#ifndef EGT_COMPARISON_BDD_FROM_BITS_BUILD_BDD_MAIN_HPP
#define EGT_COMPARISON_BDD_FROM_BITS_BUILD_BDD_MAIN_HPP


int main(int argc, char ** argv);


#endif // EGT_COMPARISON_BDD_FROM_BITS_BUILD_BDD_MAIN_HPP
