#ifndef EGT_COMPARISON_BDD_FROM_BITS_FIXED_DECISION_DIAGRAM_TYPE_TEST_HPP
#define EGT_COMPARISON_BDD_FROM_BITS_FIXED_DECISION_DIAGRAM_TYPE_TEST_HPP


#include "gtest/gtest.h"

#include "fixed_decision_diagram_type.hpp"


#endif // EGT_COMPARISON_BDD_FROM_BITS_FIXED_DECISION_DIAGRAM_TYPE_TEST_HPP
