#ifndef EGT_COMPARISON_BDD_FROM_BITS_READ_BDDS_MAIN_HPP
#define EGT_COMPARISON_BDD_FROM_BITS_READ_BDDS_MAIN_HPP


int main(int argc, char ** argv);


#endif // EGT_COMPARISON_BDD_FROM_BITS_READ_BDDS_MAIN_HPP
