#if !defined(EGT_COMPARISON_EPD_EXTENDED_POSITION_DESCRIPTION_TYPE_TEST_HPP)
#define EGT_COMPARISON_EPD_EXTENDED_POSITION_DESCRIPTION_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "epd/extended_position_description_type.hpp"


#endif // EGT_COMPARISON_EPD_EXTENDED_POSITION_DESCRIPTION_TYPE_TEST_HPP
