#if !defined(EGT_COMPARISON_REPRESENTATION_COORDINATE_TYPE_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_COORDINATE_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "representation/coordinate_type.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_COORDINATE_TYPE_TEST_HPP
