#if !defined(EGT_COMPARISON_REPRESENTATION_COVER_TYPE_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_COVER_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "representation/cover_type.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_COVER_TYPE_TEST_HPP
