#if !defined(EGT_COMPARISON_REPRESENTATION_FIGURINE_PLACEMENT_TYPE_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_FIGURINE_PLACEMENT_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "representation/figurine_placement_type.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_FIGURINE_PLACEMENT_TYPE_TEST_HPP
