#if !defined(EGT_COMPARISON_REPRESENTATION_FIGURINE_COLOUR_ENUM_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_FIGURINE_COLOUR_ENUM_TEST_HPP


#include "gtest/gtest.h"
#include "representation/figurine_colour_enum.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_FIGURINE_COLOUR_ENUM_TEST_HPP
