#if !defined(EGT_COMPARISON_REPRESENTATION_FIGURINES_TYPE_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_FIGURINES_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "representation/figurines_type.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_FIGURINES_TYPE_TEST_HPP
