#if !defined(EGT_COMPARISON_REPRESENTATION_MATERIAL_SIGNATURE_TYPE_TEST_HPP)
#define EGT_COMPARISON_REPRESENTATION_MATERIAL_SIGNATURE_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "material_signature_type.hpp"


#endif // EGT_COMPARISON_REPRESENTATION_MATERIAL_SIGNATURE_TYPE_TEST_HPP
