#!/bin/bash
sbatch <<EOF
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="build_bdd_$1_$2_$3_$4K"
#SBATCH --mem="$4K"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --requeue
#SBATCH --time="1-00:00:00"
#SBATCH --verbose
#SBATCH --open-mode=truncate

## crisgc.engr.ucr.edu
##SBATCH --partition="batch"
# cluster.hpcc.ucr.edu
#SBATCH --partition="epyc"
( ulimit -v $4; singularity exec "${APPTAINER_IMAGE_DIR}/image.sif" "${BUILD_AREA_DIR}/source/bdd_from_bits/build_bdd_main" -i "${EGT_DIR}/chesspresso/$1/$2.plb" -u $3 0 -w "${EGT_DIR}/decision_diagrams/$1/$2.$3.mtbdd" -v "${EGT_DIR}/chesspresso/$1/$2.plb" > "${EXPERIMENT_OUTPUT_TOP_DIR}/build_bdd/$1_$2_$3_$4K.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/build_bdd/$1_$2_$3_$4K.stderr" )
EOF
