#!/bin/bash
sbatch <<EOF
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="chesspressoize_$1_$2_$3_$4K"
#SBATCH --mem="$4K"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --requeue
#SBATCH --time="1-00:00:00"
#SBATCH --verbose
#SBATCH --open-mode=truncate

## crisgc.engr.ucr.edu
##SBATCH --partition="batch"
# cluster.hpcc.ucr.edu
#SBATCH --partition="epyc"
( ulimit -v $4; singularity exec "${APPTAINER_IMAGE_DIR}/image.sif" "${BUILD_AREA_DIR}/source/probe_report_nybble_processor_main" --processor=chesspresso_endgame_table_generator --canonicalization=all_symmetries --perspective=white_player --cover_count=$2 $3 > "${EXPERIMENT_OUTPUT_TOP_DIR}/chesspressoize/chesspressoize_$1_$2_$3_$4K.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/chesspressoize/chesspressoize_$1_$2_$3_$4K.stderr" )
EOF
