#!/bin/bash
sbatch <<EOF
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="d1merge_$1_$2K"
#SBATCH --mem="$2K"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --requeue
#SBATCH --time="6:00:00"
#SBATCH --verbose
#SBATCH --open-mode=truncate

## crisgc.engr.ucr.edu
##SBATCH --partition="batch"
# cluster.hpcc.ucr.edu
#SBATCH --partition="epyc"
( ulimit -v $2; singularity exec "${APPTAINER_IMAGE_DIR}/image.sif" "${BUILD_AREA_DIR}/source/generate_distance_one_cube_lists_main" $1 "" > "${EXPERIMENT_OUTPUT_TOP_DIR}/d1merge/d1merge_$1_$2K.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/d1merge/d1merge_$1_$2K.stderr" )
EOF
