#!/bin/bash
sbatch <<EOF
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="dump_environment_variables"
#SBATCH --mem="2097152K"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --requeue
#SBATCH --time="10:00"
#SBATCH --verbose
#SBATCH --open-mode=truncate

## crisgc.engr.ucr.edu
##SBATCH --partition="batch"
# cluster.hpcc.ucr.edu
#SBATCH --partition="epyc"
(
TIMESTAMP=$(date '+%Y%m%dT%H%M%S%z')
export TIMESTAMP
ulimit -v 2097152
singularity exec "${APPTAINER_IMAGE_DIR}/image.sif" "${BUILD_AREA_DIR}/source/dump_environment_variables_main" > ${EXPERIMENT_OUTPUT_TOP_DIR}/environment_variables.stdout 2> ${EXPERIMENT_OUTPUT_TOP_DIR}/environment_variables.stderr
)
EOF
