#!/bin/bash
sbatch <<EOF
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="iclize_$1_$2_$3K"
#SBATCH --mem="$3K"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --requeue
#SBATCH --time="6:00:00"
#SBATCH --verbose
#SBATCH --open-mode=truncate

## crisgc.engr.ucr.edu
##SBATCH --partition="batch"
# cluster.hpcc.ucr.edu
#SBATCH --partition="epyc"
( ulimit -v $3; singularity exec "${APPTAINER_IMAGE_DIR}/image.sif" "${BUILD_AREA_DIR}/source/convert_main" "${EGT_DIR}/cube_lists/$1/$2.clst" "${EGT_DIR}/cube_lists/$1/$2.icl" > "${EXPERIMENT_OUTPUT_TOP_DIR}/iclize/iclize_$1_$2_$3K.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/iclize/iclize_$1_$2_$3K.stderr" )
EOF
