#!/bin/bash
sbatch <<"EOF"
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="dtr_probe_timing"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --mail-user="gomboc@cs.ucr.edu"
#SBATCH --nodes=1
#SBATCH --requeue
#SBATCH --time="1-00:00:00"
#SBATCH --verbose
#SBATCH --open-mode="truncate"

# cluster.hpcc.ucr.edu -- make sure that we get an entire machine
#SBATCH --partition="epyc"
#SBATCH --cpus-per-task=256
#SBATCH --mem=0  # all available memory
# HPCC sysadmin says ${SCRATCH} points to local NVMe
( \
TIMESTAMP=$(date '+%Y%m%dT%H%M%S%z') ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/decision_dags/2" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/decision_dags/3" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/decision_dags/4" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/decision_dags/5" ; \
cp "${APPTAINER_IMAGE_DIR}/image.sif" "${SCRATCH}/${TIMESTAMP}/image.sif"; \
find "${EGT_PATH}/decision_dags/2/" -name '*.dtr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/decision_dags/2/%f\n" | sed -e "s/.dtr.xz$/.dtr/" | bash
find "${EGT_PATH}/decision_dags/3/" -name '*.dtr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/decision_dags/3/%f\n" | sed -e "s/.dtr.xz$/.dtr/" | bash
find "${EGT_PATH}/decision_dags/4/" -name '*.dtr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/decision_dags/4/%f\n" | sed -e "s/.dtr.xz$/.dtr/" | bash
find "${EGT_PATH}/decision_dags/5/" -name '*.dtr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/decision_dags/5/%f\n" | sed -e "s/.dtr.xz$/.dtr/" | bash
xzcat "${EGT_PATH}/sampled_positions/shuffled-345-figurine.epd.xz" > "${SCRATCH}/${TIMESTAMP}/shuffled-345-figurine.epd"; \
singularity exec --env "EGT_PATH=${SCRATCH}/${TIMESTAMP}" "${SCRATCH}/${TIMESTAMP}/image.sif" "${BUILD_AREA_DIR}/source/probe_timing_main" dtr 5 < "${SCRATCH}/${TIMESTAMP}/shuffled-345-figurine.epd" > "${EXPERIMENT_OUTPUT_TOP_DIR}/probe_timings/hpcc/dtr/${TIMESTAMP}.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/probe_timings/hpcc/dtr/${TIMESTAMP}.stderr" \
)
EOF
