#!/bin/bash

# While Syzygy provides tables for KN_vs_k and KB_vs_k (which are both
# always drawn), it does not provide a table for (the also always
# drawn) K_vs_k, the only two-figurine ending.  So, we'll sample only
# from endings with at least three figurines.

#./sample_uniformly_from_material_signature 2 K_vs_k 2000000
