#!/bin/bash
./sample_uniformly_from_material_signature 4 KQQ_vs_k 2000000
./sample_uniformly_from_material_signature 4 KQR_vs_k 2000000
./sample_uniformly_from_material_signature 4 KQB_vs_k 2000000
./sample_uniformly_from_material_signature 4 KQN_vs_k 2000000
./sample_uniformly_from_material_signature 4 KQP_vs_k 2000000

./sample_uniformly_from_material_signature 4 KRR_vs_k 2000000
./sample_uniformly_from_material_signature 4 KRB_vs_k 2000000
./sample_uniformly_from_material_signature 4 KRN_vs_k 2000000
./sample_uniformly_from_material_signature 4 KRP_vs_k 2000000

./sample_uniformly_from_material_signature 4 KBB_vs_k 2000000
./sample_uniformly_from_material_signature 4 KBN_vs_k 2000000
./sample_uniformly_from_material_signature 4 KBP_vs_k 2000000

./sample_uniformly_from_material_signature 4 KNN_vs_k 2000000
./sample_uniformly_from_material_signature 4 KNP_vs_k 2000000

./sample_uniformly_from_material_signature 4 KPP_vs_k 2000000
