#!/bin/bash
sbatch <<"EOF"
#!/bin/bash
#SBATCH --export="NONE"
#SBATCH --job-name="wpr_all_symmetries_probe_timing"
#SBATCH --mail-type="FAIL,INVALID_DEPEND,REQUEUE,STAGE_OUT,TIME_LIMIT"
#SBATCH --mail-user="gomboc@cs.ucr.edu"
#SBATCH --nodes=1
#SBATCH --requeue
#SBATCH --time="1-00:00:00"
#SBATCH --verbose
#SBATCH --open-mode="truncate"

# cluster.hpcc.ucr.edu -- make sure that we get an entire machine
#SBATCH --partition="epyc"
#SBATCH --cpus-per-task=256
#SBATCH --mem=0  # all available memory
# HPCC sysadmin says ${SCRATCH} points to local NVMe
( \
TIMESTAMP=$(date '+%Y%m%dT%H%M%S%z') ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/probe_report_nybble/2" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/probe_report_nybble/3" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/probe_report_nybble/4" ; \
mkdir -p "${SCRATCH}/${TIMESTAMP}/probe_report_nybble/5" ; \
cp "${APPTAINER_IMAGE_DIR}/image.sif" "${SCRATCH}/${TIMESTAMP}/image.sif"; \
find "${EGT_PATH}/probe_report_nybble/2/" -name 'K*.wpr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/probe_report_nybble/2/%f\n" | sed -e "s/.wpr.xz$/.wpr/" | bash
find "${EGT_PATH}/probe_report_nybble/3/" -name 'K*.wpr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/probe_report_nybble/3/%f\n" | sed -e "s/.wpr.xz$/.wpr/" | bash
find "${EGT_PATH}/probe_report_nybble/4/" -name 'K*.wpr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/probe_report_nybble/4/%f\n" | sed -e "s/.wpr.xz$/.wpr/" | bash
find "${EGT_PATH}/probe_report_nybble/5/" -name 'K*.wpr.xz' -printf "xzcat %h/%f > ${SCRATCH}/${TIMESTAMP}/probe_report_nybble/5/%f\n" | sed -e "s/.wpr.xz$/.wpr/" | bash
xzcat "${EGT_PATH}/sampled_positions/shuffled-345-figurine.epd.xz" > "${SCRATCH}/${TIMESTAMP}/shuffled-345-figurine.epd"; \
singularity exec --env "EGT_PATH=${SCRATCH}/${TIMESTAMP}" "${SCRATCH}/${TIMESTAMP}/image.sif" "${BUILD_AREA_DIR}/source/probe_timing_main" wpr 5 all_symmetries < "${SCRATCH}/${TIMESTAMP}/shuffled-345-figurine.epd" > "${EXPERIMENT_OUTPUT_TOP_DIR}/probe_timings/hpcc/wpr/${TIMESTAMP}.all_symmetries.stdout" 2> "${EXPERIMENT_OUTPUT_TOP_DIR}/probe_timings/hpcc/wpr/${TIMESTAMP}.all_symmetries.stderr" \
)
EOF
