#!/bin/bash

./reduce 3 KQ_vs_k D11I 11L 4194304
./reduce 3 KR_vs_k D08I 08L 4194304
./reduce 3 KB_vs_k D02I 02L 4194304
./reduce 3 KN_vs_k D02I 02L 4194304
./reduce 3 KP_vs_k D09I 09L 4194304

pushd ~/EGTs/2024-10_ECAI/cube_lists/3

ln -s -T KR_vs_k_08L.clst    KR_vs_k_11L.clst
ln -s -T KR_vs_k_08L.clst.xz KR_vs_k_11L.clst.xz
ln -s -T KR_vs_k_08L.icl     KR_vs_k_11L.icl

ln -s -T KB_vs_k_02L.clst    KB_vs_k_11L.clst
ln -s -T KB_vs_k_02L.clst.xz KB_vs_k_11L.clst.xz
ln -s -T KB_vs_k_02L.icl     KB_vs_k_11L.icl

ln -s -T KN_vs_k_02L.clst    KN_vs_k_11L.clst
ln -s -T KN_vs_k_02L.clst.xz KN_vs_k_11L.clst.xz
ln -s -T KN_vs_k_02L.icl     KN_vs_k_11L.icl

ln -s -T KP_vs_k_09L.clst    KP_vs_k_11L.clst
ln -s -T KP_vs_k_09L.clst.xz KP_vs_k_11L.clst.xz
ln -s -T KP_vs_k_09L.icl     KP_vs_k_11L.icl

popd
