#!/bin/bash
./dump_syzygy 4 KQQ_vs_k 2097152
./dump_syzygy 4 KQR_vs_k 2097152
./dump_syzygy 4 KQB_vs_k 2097152
./dump_syzygy 4 KQN_vs_k 2097152
./dump_syzygy 4 KQP_vs_k 2097152

./dump_syzygy 4 KRR_vs_k 2097152
./dump_syzygy 4 KRB_vs_k 2097152
./dump_syzygy 4 KRN_vs_k 2097152
./dump_syzygy 4 KRP_vs_k 2097152

./dump_syzygy 4 KBB_vs_k 2097152
./dump_syzygy 4 KBN_vs_k 2097152
./dump_syzygy 4 KBP_vs_k 2097152

./dump_syzygy 4 KNN_vs_k 2097152
./dump_syzygy 4 KNP_vs_k 2097152

./dump_syzygy 4 KPP_vs_k 2097152
