#!/bin/bash
./build_bdd 5 KBBB_vs_k none  33554432
./build_bdd 5 KBBB_vs_k restr 33554432
./build_bdd 5 KBBB_vs_k osm   33554432
./build_bdd 5 KBBB_vs_k tsm   33554432

./build_bdd 5 KBBN_vs_k none  33554432
./build_bdd 5 KBBN_vs_k restr 33554432
./build_bdd 5 KBBN_vs_k osm   33554432
./build_bdd 5 KBBN_vs_k tsm   33554432

./build_bdd 5 KBBP_vs_k none  33554432
./build_bdd 5 KBBP_vs_k restr 33554432
./build_bdd 5 KBBP_vs_k osm   33554432
./build_bdd 5 KBBP_vs_k tsm   33554432

./build_bdd 5 KBNN_vs_k none  33554432
./build_bdd 5 KBNN_vs_k restr 33554432
./build_bdd 5 KBNN_vs_k osm   33554432
./build_bdd 5 KBNN_vs_k tsm   33554432

./build_bdd 5 KBNP_vs_k none  33554432
./build_bdd 5 KBNP_vs_k restr 33554432
./build_bdd 5 KBNP_vs_k osm   33554432
./build_bdd 5 KBNP_vs_k tsm   33554432

./build_bdd 5 KBPP_vs_k none  33554432
./build_bdd 5 KBPP_vs_k restr 33554432
./build_bdd 5 KBPP_vs_k osm   33554432
./build_bdd 5 KBPP_vs_k tsm   33554432

./build_bdd 5 KNNN_vs_k none  33554432
./build_bdd 5 KNNN_vs_k restr 33554432
./build_bdd 5 KNNN_vs_k osm   33554432
./build_bdd 5 KNNN_vs_k tsm   33554432

./build_bdd 5 KNNP_vs_k none  33554432
./build_bdd 5 KNNP_vs_k restr 33554432
./build_bdd 5 KNNP_vs_k osm   33554432
./build_bdd 5 KNNP_vs_k tsm   33554432

./build_bdd 5 KNPP_vs_k none  33554432
./build_bdd 5 KNPP_vs_k restr 33554432
./build_bdd 5 KNPP_vs_k osm   33554432
./build_bdd 5 KNPP_vs_k tsm   33554432

./build_bdd 5 KPPP_vs_k none  33554432
./build_bdd 5 KPPP_vs_k restr 33554432
./build_bdd 5 KPPP_vs_k osm   33554432
./build_bdd 5 KPPP_vs_k tsm   33554432

./build_bdd 5 KQBB_vs_k none  33554432
./build_bdd 5 KQBB_vs_k restr 33554432
./build_bdd 5 KQBB_vs_k osm   33554432
./build_bdd 5 KQBB_vs_k tsm   33554432

./build_bdd 5 KQBN_vs_k none  33554432
./build_bdd 5 KQBN_vs_k restr 33554432
./build_bdd 5 KQBN_vs_k osm   33554432
./build_bdd 5 KQBN_vs_k tsm   33554432

./build_bdd 5 KQBP_vs_k none  67108864
./build_bdd 5 KQBP_vs_k restr 67108864
./build_bdd 5 KQBP_vs_k osm   67108864
./build_bdd 5 KQBP_vs_k tsm   67108864

./build_bdd 5 KQNN_vs_k none  33554432
./build_bdd 5 KQNN_vs_k restr 33554432
./build_bdd 5 KQNN_vs_k osm   33554432
./build_bdd 5 KQNN_vs_k tsm   33554432

./build_bdd 5 KQNP_vs_k none  33554432
./build_bdd 5 KQNP_vs_k restr 33554432
./build_bdd 5 KQNP_vs_k osm   33554432
./build_bdd 5 KQNP_vs_k tsm   33554432

./build_bdd 5 KQPP_vs_k none  33554432
./build_bdd 5 KQPP_vs_k restr 33554432
./build_bdd 5 KQPP_vs_k osm   33554432
./build_bdd 5 KQPP_vs_k tsm   33554432

./build_bdd 5 KQQB_vs_k none  33554432
./build_bdd 5 KQQB_vs_k restr 33554432
./build_bdd 5 KQQB_vs_k osm   33554432
./build_bdd 5 KQQB_vs_k tsm   33554432

./build_bdd 5 KQQN_vs_k none  33554432
./build_bdd 5 KQQN_vs_k restr 33554432
./build_bdd 5 KQQN_vs_k osm   33554432
./build_bdd 5 KQQN_vs_k tsm   33554432

./build_bdd 5 KQQP_vs_k none  33554432
./build_bdd 5 KQQP_vs_k restr 33554432
./build_bdd 5 KQQP_vs_k osm   33554432
./build_bdd 5 KQQP_vs_k tsm   33554432

./build_bdd 5 KQQQ_vs_k none  33554432
./build_bdd 5 KQQQ_vs_k restr 33554432
./build_bdd 5 KQQQ_vs_k osm   33554432
./build_bdd 5 KQQQ_vs_k tsm   33554432

./build_bdd 5 KQQR_vs_k none  33554432
./build_bdd 5 KQQR_vs_k restr 33554432
./build_bdd 5 KQQR_vs_k osm   33554432
./build_bdd 5 KQQR_vs_k tsm   33554432

./build_bdd 5 KQRB_vs_k none  33554432
./build_bdd 5 KQRB_vs_k restr 33554432
./build_bdd 5 KQRB_vs_k osm   33554432
./build_bdd 5 KQRB_vs_k tsm   33554432

./build_bdd 5 KQRN_vs_k none  33554432
./build_bdd 5 KQRN_vs_k restr 33554432
./build_bdd 5 KQRN_vs_k osm   33554432
./build_bdd 5 KQRN_vs_k tsm   33554432

./build_bdd 5 KQRP_vs_k none  33554432
./build_bdd 5 KQRP_vs_k restr 33554432
./build_bdd 5 KQRP_vs_k osm   33554432
./build_bdd 5 KQRP_vs_k tsm   33554432

./build_bdd 5 KQRR_vs_k none  33554432
./build_bdd 5 KQRR_vs_k restr 33554432
./build_bdd 5 KQRR_vs_k osm   33554432
./build_bdd 5 KQRR_vs_k tsm   33554432

./build_bdd 5 KRBB_vs_k none  33554432
./build_bdd 5 KRBB_vs_k restr 33554432
./build_bdd 5 KRBB_vs_k osm   33554432
./build_bdd 5 KRBB_vs_k tsm   33554432

./build_bdd 5 KRBN_vs_k none  33554432
./build_bdd 5 KRBN_vs_k restr 33554432
./build_bdd 5 KRBN_vs_k osm   33554432
./build_bdd 5 KRBN_vs_k tsm   33554432

./build_bdd 5 KRBP_vs_k none  33554432
./build_bdd 5 KRBP_vs_k restr 33554432
./build_bdd 5 KRBP_vs_k osm   33554432
./build_bdd 5 KRBP_vs_k tsm   33554432

./build_bdd 5 KRNN_vs_k none  33554432
./build_bdd 5 KRNN_vs_k restr 33554432
./build_bdd 5 KRNN_vs_k osm   33554432
./build_bdd 5 KRNN_vs_k tsm   33554432

./build_bdd 5 KRNP_vs_k none  33554432
./build_bdd 5 KRNP_vs_k restr 33554432
./build_bdd 5 KRNP_vs_k osm   33554432
./build_bdd 5 KRNP_vs_k tsm   33554432

./build_bdd 5 KRPP_vs_k none  33554432
./build_bdd 5 KRPP_vs_k restr 33554432
./build_bdd 5 KRPP_vs_k osm   33554432
./build_bdd 5 KRPP_vs_k tsm   33554432

./build_bdd 5 KRRB_vs_k none  33554432
./build_bdd 5 KRRB_vs_k restr 33554432
./build_bdd 5 KRRB_vs_k osm   33554432
./build_bdd 5 KRRB_vs_k tsm   33554432

./build_bdd 5 KRRN_vs_k none  33554432
./build_bdd 5 KRRN_vs_k restr 33554432
./build_bdd 5 KRRN_vs_k osm   33554432
./build_bdd 5 KRRN_vs_k tsm   33554432

./build_bdd 5 KRRP_vs_k none  33554432
./build_bdd 5 KRRP_vs_k restr 33554432
./build_bdd 5 KRRP_vs_k osm   33554432
./build_bdd 5 KRRP_vs_k tsm   33554432

./build_bdd 5 KRRR_vs_k none  33554432
./build_bdd 5 KRRR_vs_k restr 33554432
./build_bdd 5 KRRR_vs_k osm   33554432
./build_bdd 5 KRRR_vs_k tsm   33554432
