#if !defined(EGT_COMPARISON_CHESSPRESSO_PROBE_TIMING_EPD_PARSING_TEST_HPP)
#define EGT_COMPARISON_CHESSPRESSO_PROBE_TIMING_EPD_PARSING_TEST_HPP


#include "gtest/gtest.h"
#include "chesspresso_probe_timing_epd_parsing.hpp"


#endif // EGT_COMPARISON_CHESSPRESSO_PROBE_TIMING_EPD_PARSING_TEST_HPP
