#if !defined(EGT_COMPARISON_CHESSPRESSO_ENDGAME_TABLE_TYPE_TEST_HPP)
#define EGT_COMPARISON_CHESSPRESSO_ENDGAME_TABLE_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "chesspresso_endgame_table_type.hpp"


#endif // EGT_COMPARISON_CHESSPRESSO_ENDGAME_TABLE_TYPE_TEST_HPP
