#if !defined(EGT_COMPARISON_GENERATE_DISTANCE_ONE_CUBE_LISTS_MAIN_HPP)
#define EGT_COMPARISON_GENERATE_DISTANCE_ONE_CUBE_LISTS_MAIN_HPP


int main(int argc, char *argv[]);


#endif // EGT_COMPARISON_GENERATE_DISTANCE_ONE_CUBE_LISTS_MAIN_HPP
