#ifndef EGT_COMPARISON_GENERATE_STATUS_BOARD_MAIN_HPP
#define EGT_COMPARISON_GENERATE_STATUS_BOARD_MAIN_HPP


int main(int argc, char * argv[]);


#endif // EGT_COMPARISON_GENERATE_STATUS_BOARD_MAIN_HPP
