#ifndef EGT_COMPARISON_GENERATE_MATERIAL_SIGNATURES_MAIN_HPP
#define EGT_COMPARISON_GENERATE_MATERIAL_SIGNATURES_MAIN_HPP


int main(int argc, char * argv[]);


#endif // EGT_COMPARISON_GENERATE_MATERIAL_SIGNATURES_MAIN_HPP
