#if !defined(EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOTTER_TYPE_TEST_HPP)
#define EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOTTER_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "memory_information_snapshotter_type.hpp"


#endif // EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOTTER_TYPE_TEST_HPP
