#if !defined(EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOT_TYPE_TEST_HPP)
#define EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOT_TYPE_TEST_HPP


#include "gtest/gtest.h"
#include "memory_information_snapshot_type.hpp"


#endif // EGT_COMPARISON_MEMORY_INFORMATION_SNAPSHOT_TYPE_TEST_HPP
