#ifndef EGT_COMPARISON_SYNCHRONIZED_SHUFFLE_TEST_HPP
#define EGT_COMPARISON_SYNCHRONIZED_SHUFFLE_TEST_HPP


#include "gtest/gtest.h"

#include "synchronized_shuffle.hpp"


#endif // EGT_COMPARISON_SYNCHRONIZED_SHUFFLE_TEST_HPP
