#if !defined(EGT_COMPARISON_SYZYGY_POSITION_PROCESSOR_MAIN_HPP)
#define EGT_COMPARISON_SYZYGY_POSITION_PROCESSOR_MAIN_HPP


int main(int argc, char *argv[]);


#endif // EGT_COMPARISON_SYZYGY_POSITION_PROCESSOR_MAIN_HPP
